// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: wx_mp_login.proto

package weixin_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 微信小程序登录请求参数
type MpLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrantType string `protobuf:"bytes,1,opt,name=GrantType,proto3" json:"GrantType,omitempty"`
	JsCode    string `protobuf:"bytes,2,opt,name=JsCode,proto3" json:"JsCode,omitempty"`
	Secret    string `protobuf:"bytes,3,opt,name=Secret,proto3" json:"Secret,omitempty"`
	AppId     string `protobuf:"bytes,4,opt,name=AppId,proto3" json:"AppId,omitempty"`
}

func (x *MpLoginRequest) Reset() {
	*x = MpLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_mp_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpLoginRequest) ProtoMessage() {}

func (x *MpLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wx_mp_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpLoginRequest.ProtoReflect.Descriptor instead.
func (*MpLoginRequest) Descriptor() ([]byte, []int) {
	return file_wx_mp_login_proto_rawDescGZIP(), []int{0}
}

func (x *MpLoginRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *MpLoginRequest) GetJsCode() string {
	if x != nil {
		return x.JsCode
	}
	return ""
}

func (x *MpLoginRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *MpLoginRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// 微信小程序登录返回参数
type MpLoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnionId    string `protobuf:"bytes,1,opt,name=UnionId,proto3" json:"UnionId,omitempty"`
	OpenId     string `protobuf:"bytes,2,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	SessionKey string `protobuf:"bytes,3,opt,name=SessionKey,proto3" json:"SessionKey,omitempty"`
}

func (x *MpLoginReply) Reset() {
	*x = MpLoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_mp_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpLoginReply) ProtoMessage() {}

func (x *MpLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_wx_mp_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpLoginReply.ProtoReflect.Descriptor instead.
func (*MpLoginReply) Descriptor() ([]byte, []int) {
	return file_wx_mp_login_proto_rawDescGZIP(), []int{1}
}

func (x *MpLoginReply) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

func (x *MpLoginReply) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *MpLoginReply) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

// 微信小程序手机号授权
type MpPhoneNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	OpenId string `protobuf:"bytes,2,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	Secret string `protobuf:"bytes,3,opt,name=Secret,proto3" json:"Secret,omitempty"`
	AppId  string `protobuf:"bytes,4,opt,name=AppId,proto3" json:"AppId,omitempty"`
}

func (x *MpPhoneNumberRequest) Reset() {
	*x = MpPhoneNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_mp_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpPhoneNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpPhoneNumberRequest) ProtoMessage() {}

func (x *MpPhoneNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wx_mp_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpPhoneNumberRequest.ProtoReflect.Descriptor instead.
func (*MpPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return file_wx_mp_login_proto_rawDescGZIP(), []int{2}
}

func (x *MpPhoneNumberRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MpPhoneNumberRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *MpPhoneNumberRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *MpPhoneNumberRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// 微信小程序手机号授权
type MpPhoneNumberReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber     string     `protobuf:"bytes,1,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	PurePhoneNumber string     `protobuf:"bytes,2,opt,name=PurePhoneNumber,proto3" json:"PurePhoneNumber,omitempty"`
	CountryCode     int32      `protobuf:"varint,3,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
	Watermark       *Watermark `protobuf:"bytes,4,opt,name=Watermark,proto3" json:"Watermark,omitempty"`
}

func (x *MpPhoneNumberReply) Reset() {
	*x = MpPhoneNumberReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_mp_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpPhoneNumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpPhoneNumberReply) ProtoMessage() {}

func (x *MpPhoneNumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_wx_mp_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpPhoneNumberReply.ProtoReflect.Descriptor instead.
func (*MpPhoneNumberReply) Descriptor() ([]byte, []int) {
	return file_wx_mp_login_proto_rawDescGZIP(), []int{3}
}

func (x *MpPhoneNumberReply) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *MpPhoneNumberReply) GetPurePhoneNumber() string {
	if x != nil {
		return x.PurePhoneNumber
	}
	return ""
}

func (x *MpPhoneNumberReply) GetCountryCode() int32 {
	if x != nil {
		return x.CountryCode
	}
	return 0
}

func (x *MpPhoneNumberReply) GetWatermark() *Watermark {
	if x != nil {
		return x.Watermark
	}
	return nil
}

// 微信小程序手机号授权数据水印
type Watermark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     string `protobuf:"bytes,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	Timestamp int32  `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *Watermark) Reset() {
	*x = Watermark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_mp_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Watermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watermark) ProtoMessage() {}

func (x *Watermark) ProtoReflect() protoreflect.Message {
	mi := &file_wx_mp_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watermark.ProtoReflect.Descriptor instead.
func (*Watermark) Descriptor() ([]byte, []int) {
	return file_wx_mp_login_proto_rawDescGZIP(), []int{4}
}

func (x *Watermark) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Watermark) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_wx_mp_login_proto protoreflect.FileDescriptor

var file_wx_mp_login_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x78, 0x5f, 0x6d, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x5f, 0x70, 0x62, 0x22, 0x74,
	0x0a, 0x0e, 0x4d, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x4a, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4a, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41,
	0x70, 0x70, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x0c, 0x4d, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x22, 0x70, 0x0a, 0x14, 0x4d, 0x70, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x22, 0xb6, 0x01, 0x0a, 0x12, 0x4d, 0x70, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x28, 0x0a, 0x0f, 0x50, 0x75, 0x72, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x50, 0x75, 0x72, 0x65,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a,
	0x09, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x5f, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74,
	0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x09, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72,
	0x6b, 0x22, 0x3f, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x32, 0xa5, 0x01, 0x0a, 0x09, 0x57, 0x78, 0x4d, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x44, 0x0a, 0x0c, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x19, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x5f, 0x70, 0x62, 0x2e, 0x4d, 0x70, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x77, 0x65,
	0x69, 0x78, 0x69, 0x6e, 0x5f, 0x70, 0x62, 0x2e, 0x4d, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69,
	0x6e, 0x5f, 0x70, 0x62, 0x2e, 0x4d, 0x70, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x65, 0x69, 0x78,
	0x69, 0x6e, 0x5f, 0x70, 0x62, 0x2e, 0x4d, 0x70, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2e,
	0x2f, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x5f, 0x70, 0x62, 0x3b, 0x77, 0x65, 0x69, 0x78, 0x69,
	0x6e, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wx_mp_login_proto_rawDescOnce sync.Once
	file_wx_mp_login_proto_rawDescData = file_wx_mp_login_proto_rawDesc
)

func file_wx_mp_login_proto_rawDescGZIP() []byte {
	file_wx_mp_login_proto_rawDescOnce.Do(func() {
		file_wx_mp_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_wx_mp_login_proto_rawDescData)
	})
	return file_wx_mp_login_proto_rawDescData
}

var file_wx_mp_login_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wx_mp_login_proto_goTypes = []interface{}{
	(*MpLoginRequest)(nil),       // 0: weixin_pb.MpLoginRequest
	(*MpLoginReply)(nil),         // 1: weixin_pb.MpLoginReply
	(*MpPhoneNumberRequest)(nil), // 2: weixin_pb.MpPhoneNumberRequest
	(*MpPhoneNumberReply)(nil),   // 3: weixin_pb.MpPhoneNumberReply
	(*Watermark)(nil),            // 4: weixin_pb.Watermark
}
var file_wx_mp_login_proto_depIdxs = []int32{
	4, // 0: weixin_pb.MpPhoneNumberReply.Watermark:type_name -> weixin_pb.Watermark
	0, // 1: weixin_pb.WxMpLogin.Code2Session:input_type -> weixin_pb.MpLoginRequest
	2, // 2: weixin_pb.WxMpLogin.GetPhoneNumber:input_type -> weixin_pb.MpPhoneNumberRequest
	1, // 3: weixin_pb.WxMpLogin.Code2Session:output_type -> weixin_pb.MpLoginReply
	3, // 4: weixin_pb.WxMpLogin.GetPhoneNumber:output_type -> weixin_pb.MpPhoneNumberReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wx_mp_login_proto_init() }
func file_wx_mp_login_proto_init() {
	if File_wx_mp_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wx_mp_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_mp_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpLoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_mp_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpPhoneNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_mp_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpPhoneNumberReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_mp_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Watermark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wx_mp_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wx_mp_login_proto_goTypes,
		DependencyIndexes: file_wx_mp_login_proto_depIdxs,
		MessageInfos:      file_wx_mp_login_proto_msgTypes,
	}.Build()
	File_wx_mp_login_proto = out.File
	file_wx_mp_login_proto_rawDesc = nil
	file_wx_mp_login_proto_goTypes = nil
	file_wx_mp_login_proto_depIdxs = nil
}
