// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: ali_mp_login.proto

package aliyun_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付宝小程序登录请求参数
type MpLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrantType    string `protobuf:"bytes,1,opt,name=GrantType,proto3" json:"GrantType,omitempty"`
	Code         string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	AppId        string `protobuf:"bytes,4,opt,name=AppId,proto3" json:"AppId,omitempty"`
}

func (x *MpLoginRequest) Reset() {
	*x = MpLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ali_mp_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpLoginRequest) ProtoMessage() {}

func (x *MpLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ali_mp_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpLoginRequest.ProtoReflect.Descriptor instead.
func (*MpLoginRequest) Descriptor() ([]byte, []int) {
	return file_ali_mp_login_proto_rawDescGZIP(), []int{0}
}

func (x *MpLoginRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *MpLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MpLoginRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *MpLoginRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// 支付宝小程序登录返回参数
type MpLoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OpenId      string `protobuf:"bytes,2,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	AccessToken string `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
}

func (x *MpLoginReply) Reset() {
	*x = MpLoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ali_mp_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpLoginReply) ProtoMessage() {}

func (x *MpLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_ali_mp_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpLoginReply.ProtoReflect.Descriptor instead.
func (*MpLoginReply) Descriptor() ([]byte, []int) {
	return file_ali_mp_login_proto_rawDescGZIP(), []int{1}
}

func (x *MpLoginReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MpLoginReply) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *MpLoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 支付宝小程序用户信息请求参数
type MpUserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthToken string `protobuf:"bytes,1,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
	AppId     string `protobuf:"bytes,2,opt,name=AppId,proto3" json:"AppId,omitempty"`
}

func (x *MpUserInfoRequest) Reset() {
	*x = MpUserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ali_mp_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpUserInfoRequest) ProtoMessage() {}

func (x *MpUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ali_mp_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpUserInfoRequest.ProtoReflect.Descriptor instead.
func (*MpUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_ali_mp_login_proto_rawDescGZIP(), []int{2}
}

func (x *MpUserInfoRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *MpUserInfoRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// 支付宝小程序用户信息返回参数
type MpUserInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OpenId   string `protobuf:"bytes,2,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	City     string `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	NickName string `protobuf:"bytes,5,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Province string `protobuf:"bytes,6,opt,name=Province,proto3" json:"Province,omitempty"`
	Gender   string `protobuf:"bytes,7,opt,name=Gender,proto3" json:"Gender,omitempty"`
}

func (x *MpUserInfoReply) Reset() {
	*x = MpUserInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ali_mp_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MpUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpUserInfoReply) ProtoMessage() {}

func (x *MpUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_ali_mp_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpUserInfoReply.ProtoReflect.Descriptor instead.
func (*MpUserInfoReply) Descriptor() ([]byte, []int) {
	return file_ali_mp_login_proto_rawDescGZIP(), []int{3}
}

func (x *MpUserInfoReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MpUserInfoReply) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *MpUserInfoReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *MpUserInfoReply) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *MpUserInfoReply) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *MpUserInfoReply) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *MpUserInfoReply) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

var File_ali_mp_login_proto protoreflect.FileDescriptor

var file_ali_mp_login_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x6c, 0x69, 0x5f, 0x6d, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x5f, 0x70, 0x62, 0x22,
	0x7c, 0x0a, 0x0e, 0x4d, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x22, 0x60, 0x0a,
	0x0c, 0x4d, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x47, 0x0a, 0x11, 0x4d, 0x70, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x22, 0xbd, 0x01, 0x0a, 0x0f, 0x4d, 0x70, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x32, 0xa3, 0x01, 0x0a, 0x0a, 0x41, 0x6c, 0x69,
	0x4d, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x48, 0x0a, 0x10, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x2e, 0x61, 0x6c,
	0x69, 0x79, 0x75, 0x6e, 0x5f, 0x70, 0x62, 0x2e, 0x4d, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x5f,
	0x70, 0x62, 0x2e, 0x4d, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x4b, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x12, 0x1c, 0x2e, 0x61, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x5f, 0x70, 0x62, 0x2e, 0x4d,
	0x70, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x61, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x5f, 0x70, 0x62, 0x2e, 0x4d, 0x70, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x18,
	0x5a, 0x16, 0x2e, 0x2e, 0x2f, 0x61, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x5f, 0x70, 0x62, 0x3b, 0x61,
	0x6c, 0x69, 0x79, 0x75, 0x6e, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ali_mp_login_proto_rawDescOnce sync.Once
	file_ali_mp_login_proto_rawDescData = file_ali_mp_login_proto_rawDesc
)

func file_ali_mp_login_proto_rawDescGZIP() []byte {
	file_ali_mp_login_proto_rawDescOnce.Do(func() {
		file_ali_mp_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_ali_mp_login_proto_rawDescData)
	})
	return file_ali_mp_login_proto_rawDescData
}

var file_ali_mp_login_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ali_mp_login_proto_goTypes = []interface{}{
	(*MpLoginRequest)(nil),    // 0: aliyun_pb.MpLoginRequest
	(*MpLoginReply)(nil),      // 1: aliyun_pb.MpLoginReply
	(*MpUserInfoRequest)(nil), // 2: aliyun_pb.MpUserInfoRequest
	(*MpUserInfoReply)(nil),   // 3: aliyun_pb.MpUserInfoReply
}
var file_ali_mp_login_proto_depIdxs = []int32{
	0, // 0: aliyun_pb.AliMpLogin.SystemOauthToken:input_type -> aliyun_pb.MpLoginRequest
	2, // 1: aliyun_pb.AliMpLogin.UserInfoShare:input_type -> aliyun_pb.MpUserInfoRequest
	1, // 2: aliyun_pb.AliMpLogin.SystemOauthToken:output_type -> aliyun_pb.MpLoginReply
	3, // 3: aliyun_pb.AliMpLogin.UserInfoShare:output_type -> aliyun_pb.MpUserInfoReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ali_mp_login_proto_init() }
func file_ali_mp_login_proto_init() {
	if File_ali_mp_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ali_mp_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ali_mp_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpLoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ali_mp_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpUserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ali_mp_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MpUserInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ali_mp_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ali_mp_login_proto_goTypes,
		DependencyIndexes: file_ali_mp_login_proto_depIdxs,
		MessageInfos:      file_ali_mp_login_proto_msgTypes,
	}.Build()
	File_ali_mp_login_proto = out.File
	file_ali_mp_login_proto_rawDesc = nil
	file_ali_mp_login_proto_goTypes = nil
	file_ali_mp_login_proto_depIdxs = nil
}
